name: Build and download wheel
on: workflow_dispatch


jobs:


  build-wheel:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest, ubuntu-20.04,  macos-latest,  windows-2019,	macos-13,  macos-11]
        python-version: [ "3.8", "3.9", "3.10","3.11", "3.12"]

    steps:
      - uses: actions/checkout@v2
      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: build wheel
        run: |
          mkdir -p path/to/artifact
          pip install --upgrade pip
          pip install --upgrade setuptools
          pip install pybind11
          pip install wheel
          python setup.py bdist_wheel
          ls
      - uses: actions/upload-artifact@v3
        with:
           name: my-artifact
           path: dist/ # or path/to/artifact

        
          
#       - name: upload_artifact
#       - uses: actions/checkout@v3

#       - uses: actions/download-artifact@v3
#         with:
#           name: my-artifact
#           path: dist/
    
#       - name: Display structure of downloaded files
#         run: ls -R
#         working-directory: path/to/artifact
        
#   upload_artifact:
#    runs-on: ${{ matrix.os }}
#    strategy:
#       matrix:
#         os: [ windows-latest ]
#         python-version: [ 3.8, 3.9 ]
#    steps:
#      - uses: actions/checkout@v3

#      - run: mkdir -p path/to/artifact

#      - run: echo hello > path/to/artifact/world.txt

#      - uses: actions/upload-artifact@v3
#        with:
#          name: my-artifact
#          path: path/to/artifact/ # or path/to/artifact

